pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                script{
                    sh 'cd chennai'
                    sh 'mvn clean install -X'}
                    
            }
        }
    }
}
