pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                script{
                    sh ''' cd /home/user/.jenkins/workspace/sampleProject2/chennai 
                    mvn clean install -X '''
                   
                    
            }
        }
    }
}
