pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                script{
                    sh 'cd /home/user/.jenkins/workspace/sampleProject2/chennai'
                    sh ' ls -lart'
                    sh 'mvn clean install -X'}
                    
            }
        }
    }
}
